# Generated by Django 5.0.4 on 2024-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_registration_code_alter_user_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_code_flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='без имени'),
        ),
    ]
