# Generated by Django 5.0.4 on 2024-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_registration_code_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_code_flag',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='без имени'),
        ),
    ]
