# Generated by Django 5.0.4 on 2024-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_user_registration_code_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код учёта'),
        ),
    ]
